### ISSUE TITLE
why aren't they equal?

### ISSUE THREAD

**Issue by JackXuXin** [bluebird75/luaunit#120] opened 2019-04-10 09:19 UTC
![image](https://user-images.githubusercontent.com/24310518/55867265-60520000-5bac-11e9-8744-a032eca26954.png)

**Comment by bluebird75** [comment] 2019-04-24 18:05
That looks strange indeed. I'll try to have a look

**Comment by bluebird75** [comment] 2019-04-24 18:44
I tried to reproduce your problem but did not succeed. Which version of Lua and LuaUnit are you using ? Is the content of the table really what is being displayed ?

**Comment by bluebird75** [comment] 2019-04-24 18:49
```$ lua52
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> lu = require('luaunit')
> lu.assertEquals( {1}, {1.0} )
> lu.assertEquals( {a=1}, {a=1.0} )
> lu.assertEquals( 1, 2 )
stdin:1: LuaUnit test FAILURE: expected: 2, actual: 1
stack traceback:
        [C]: in function 'error'
        ./luaunit.lua:1190: in function 'failure'
        ./luaunit.lua:1276: in function 'assertEquals'
        stdin:1: in main chunk
        [C]: in ?
> lu.assertEquals( {free=0, multiple=17}, {free=0, multiple=17.0} ) -- see, no error generated
> ^Z

$ lua51
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> lu = require('luaunit')
> lu.assertEquals( {free=0, multiple=17}, {free=0, multiple=17.0} ) -- see, no error generated
> ^Z

$ lua53
Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> lu = require('luaunit')
> lu.assertEquals( {free=0, multiple=17}, {free=0, multiple=17.0} ) -- see, no error generated
> ^Z

$
```

**Comment by bluebird75** [comment] 2019-04-27 13:10
Can you check with the master version of LuaUnit ? It could be a duplicate of #122 which I just closed.

**Comment by bluebird75** [comment] 2019-06-12 20:28
Closing after lack of feedback and no reproducability.

**Closed by bluebird75** 2019-06-12 20:28 UTC
